### ISSUE TITLE
Media Extract Feature Request

### ISSUE THREAD

**Issue by robweld** [Skeletonxf/image-extract#5]
Love the extension. Could you make it so video - MP4, WebM, and Ogg - will also be extracted? As they are the three formats supported in HTML.

**Comment by Skeletonxf** [comment]
Video support is definitely something I can look into.

Unfortunately I refactored Image Extract while adding support for manifest version 3 and was very close to releasing it when I ran into a very annoying issue in Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1851083 that's still not resolved. I don't want to continue working on the pre refactor code base since it's multiple years out of date but also don't want to release a new version at the moment while that issue remains, so any new features might not see a release to addons.mozilla.org for a while.

**Comment by robweld** [comment]
Twitter, Instagram, or Facebook come to mind. No worries if it's a bit of a big ask!

**Comment by Skeletonxf** [comment]
I've only been looking at videos but I suspect this applies equally to audio.

This seems **very hard**, since videos are typically embedded within an iframe which makes accessing them via an addon more difficult, and then even if accessed, typically they use blob sources which [cannot be hotlinked](https://stackoverflow.com/questions/30864573/what-is-a-blob-url-and-why-it-is-used) and I've ran into issues trying to reuse a blob URL within the content script even staying on the same webpage

 > Security Error: Content at moz-extension://9c5a3802-98cb-457a-9b12-3d53ff0845de/ may not load data from blob:...

As Image Extract was originally created for images only, and this seems quite difficult I don't want to add a lot of maintenance burden on extending it to video or audio. You might find it's possible to use a non browser tool or picture in picture instead depending on use case.

**Comment by robweld** [comment]
> As Image Extract was originally created for images only, and this seems quite difficult I don't want to add a lot of maintenance burden on extending it to video or audio.

Yes it's out of the scope turning the addon into more of a media extractor; and from the limited research I've done it does seem to be a real hassle. I do have a suggestion for a different method achieving pretty much the same end goal that you might want to try @Skeletonxf.

So my initial idea was to effectively just alter the css for everything (apart from media players) to be 'display: none;'. Optionally set at the max resolution but this isn't something I would be too fussed about; as mainly the thing I like most about the current addon is less about getting the max version of the images but to view the page without all the 'fluff'. 

Cheers for taking the time to look into it at all in the first place, and if my suggested solution is something that you would be interested in trying to add I would appreciate it!

**Comment by Skeletonxf** [comment]
Stripping everything from the page via CSS might side step some of these issues yes. However it's probably not the direction I want to go since I've had at least one negative user review about losing work due to running the add-on accidentally as well as occasional minor but annoying issues when a site's existing CSS clashes with the inserted Image Extract UI https://github.com/Skeletonxf/image-extract/issues/1 Long term I'd want to see if I can make Image Extract open a new extension page when it's ran so the user doesn't lose the page they were on which would fix these issues, but make the hide-everything-with-css approach no longer viable.

For this sort of CSS solution you might be able to get away with a user-script addon and maybe something like
```
* {
    display: none;
}

img, video, audio {
  display: initial;
}
```

**Comment by robweld** [comment]
As I believe when display is set to hidden it isn't loaded at all, even the child css, but changing it to visibility: hidden/visible would work but it seems as if at least youtube doesn't class thumbnails as an img or video :D
![Screenshot 2024-04-27 221755](https://github.com/Skeletonxf/image-extract/assets/43070503/2cbfa732-9214-4e5e-a92f-44e8f59ce9d1)
